### ISSUE TITLE
Periodic errors on run trello bot via cron job

### ISSUE THREAD

**Issue by dimti** [somebox/jira-tracker-for-trello#9]
My trello jira bot installation works is fine, but some time i see errors after run periodic cron job (every 24 minutes)

1.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:115:in `new_commands'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:46:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-16T09:06:13.755976 #24969] ERROR -- : [ GET https://api.trello.com/1/cards/56e400363e34fcb750b8e2a1/actions?filter=commentCard]: 
```

2.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:119:in `last_posting_date'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:42:in `update_resolution_status'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:67:in `block (2 levels) in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:66:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:66:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-16T08:49:11.493133 #24719] ERROR -- : [ GET https://api.trello.com/1/cards/56497f15a8aa9153cc1e10ad/actions?filter=commentCard]:
```

3.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:119:in `last_posting_date'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:72:in `update_attachments_from_jira'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:60:in `block (2 levels) in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:59:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:59:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-16T08:26:59.922149 #24183] ERROR -- : [ GET https://api.trello.com/1/cards/5770e5ff7078557355df0edb/actions?filter=commentCard]: 
```

4.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:119:in `last_posting_date'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:58:in `update_comments_from_jira'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:53:in `block (2 levels) in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:52:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:52:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-15T19:24:51.092113 #9763] ERROR -- : [ GET https://api.trello.com/1/cards/5614a899d674928211713154/actions?filter=commentCard]:
```

5.

```
/var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:427:in `rescue in transmit': Request Timeout (RestClient::RequestTimeout)
from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:350:in `transmit'
from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/resource.rb:51:in `get'
from /opt/jira-tracker-for-trello/lib/jira/client.rb:15:in `get'
from /opt/jira-tracker-for-trello/lib/jira/ticket.rb:72:in `exists?'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:138:in `jira_ticket_exists?'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:123:in `track_jira'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:146:in `block in update_tracking_status'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:143:in `each'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:143:in `update_tracking_status'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:40:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
```

6.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:119:in `last_posting_date'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:42:in `update_resolution_status'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:67:in `block (2 levels) in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:66:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:66:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-15T17:50:08.373120 #7890] ERROR -- : [ GET https://api.trello.com/1/cards/56497e308c86051fa740dd3f/actions?filter=commentCard]: 
```

7.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:44:in `find'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/basic_data.rb:80:in `block (2 levels) in one'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:26:in `summary'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:39:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-15T17:25:38.764014 #7307] ERROR -- : [ GET https://api.trello.com/1/boards/55dc2f2011f5323c574240fd]: 
```

8.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:111:in `commands'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:143:in `update_tracking_status'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:40:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-15T16:52:37.891612 #6703] ERROR -- : [ GET https://api.trello.com/1/cards/56bf3cf02573255b4ea96aa0/actions?filter=commentCard]: 
```

9.

```
/home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:99:in `invoke_verb': Trello::Error (Trello::Error)
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/client.rb:19:in `get'
from /home/dimti/.bundler/ruby/1.9.1/ruby-trello-8f240c98cea2/lib/trello/has_actions.rb:5:in `actions'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:106:in `comment_scanner'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:119:in `last_posting_date'
from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:58:in `update_comments_from_jira'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:53:in `block (2 levels) in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:52:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:52:in `block in update'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
from ./bin/trello-jira-bot:29:in `<main>'
E, [2016-08-15T12:49:50.409617 #2892] ERROR -- : [ GET https://api.trello.com/1/cards/572c1d06b5cb25935ff3fb7d/actions?filter=commentCard]: 
```

Cron job executes every 24 minute. But errors not permanently after run trello bot. Where errors are critical and where errors is notice? How to fix it, if is possible?

**Comment by somebox** [comment]
This could be temporary problems from the Trello API, or an issue with the network. Maybe check the ruby-trello gem issues to see if anyone had a problem there?
